--CREATE USER fusion IDENTIFIED BY fusion;
--GRANT CONNECT, RESOURCE, SYSDBA TO fusion;

CREATE TABLE TB_BOARD (
	BOARD_ID	NUMBER(19) PRIMARY KEY NOT NULL,
	TITLE	VARCHAR2(500),
	CONTENT	VARCHAR(4000),
	WRITER NUMBER(50),
	BOARD_CNT NUMBER(19),
	DEL_YN VARCHAR2(1) DEFAULT 'N',
	REGIST_DT DATE,
	UPDATE_DT DATE
);

CREATE TABLE TB_USER (
	USER_ID	NUMBER(19) PRIMARY KEY NOT NULL,
	ID	VARCHAR2(50),
	PWD VARCHAR2(100),
	NCNM VARCHAR2(50),
	REGIST_DT DATE,
	UPDATE_DT DATE
);



CREATE SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_USER;

INSERT INTO TB_USER VALUES (1, 'fusion', 'Fusion!@34', '퓨전인',SYSDATE,SYSDATE);


COMMIT;